apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tpl (toYaml .Values.metadata.name) . }}
  labels:
    {{- tpl (toYaml .Values.metadata.labels) . | nindent 4 }}
data:
  SERVICE_URL: "{{ .Values.SERVICE_URL}}"
  LOG_LEVEL: "INFO"
  HOST: "0.0.0.0"
  PORT: "{{ .Values.service.targetPort }}"
  DEBUG: "False"